# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f8d58d13a2661efaca3a7d8620fcf45bf2c3a3d999d3386fd5c89cc6be6cb074661fbacf4ec6619cf1ebf5cd432cbb08ad9b595bab01d4a45b48b40ffda6756

test:
  secret_key_base: f3e886ea248ae6da409d6840220d99e2f1744c61a3037abbae75606ee3417b4813f84c1400a90b82a4eb43f96a52ba398586b8d6298196276a0141630f07bf05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
